### PR TITLE
[FIX] compile issue (not declare TRUE and FALSE)

### PR DESCRIPTION
**Pull request by pino-kim**
-The intent of your change.
	1. Fix compile issue (not declare TRUE and FALSE) 
	
- Short log / Statement of what needed to be changed.
        1. Add stdbool.h
	2. declared TRUE, FALSE (Jason header remove it) again.
	3. If previous json-c already declared, skip it.

- distro version
	ubuntu 16.04.05  64bit
	
-Signed-off-by: pino-kim sungwon.pino@gmail.com

### CODE REVIEW

**Comment by pino-kim** [comment]
dear @jlelli

**Comment by jlelli** [comment]
Please have a look at my reply here https://github.com/scheduler-tools/rt-app/issues/62

**Comment by pino-kim** [comment]
@jlelli Ok thanks your comment .
Do you want to close this PR?

**Comment by jlelli** [comment]
Not at all. As discussed in #62 we want to fix this issue once for all.
You current solution however has problems with json-c version that defines TRUE/FALSE already:
```
rt-app_parse_config.c:41: warning: "TRUE" redefined
 #define TRUE true

In file included from /usr/include/json-c/linkhash.h:22,
                 from /usr/include/json-c/json.h:25,
                 from rt-app_parse_config.c:29:
/usr/include/json-c/json_object.h:125: note: this is the location of the previous definition
 #define TRUE ((json_bool)1)

rt-app_parse_config.c:42: warning: "FALSE" redefined
 #define FALSE false

In file included from /usr/include/json-c/linkhash.h:22,
                 from /usr/include/json-c/json.h:25,
                 from rt-app_parse_config.c:29:
/usr/include/json-c/json_object.h:122: note: this is the location of the previous definition
 #define FALSE ((json_bool)0)
```
Guess we need to undef them before defining our version?

**Comment by pino-kim** [comment]
dear @jlelli, @v0lker
I appreciate my poor PR description. I modify  
it as soon as possible. below is what i  install rt-app right on my computer. 

1. What I expect
expect compile done.
but get error log.

2. What I do
 - install ubuntu 16.04.05 (Oracle virtualbox 5.2.18)
 
 - Install prerequisites
	sudo apt install git
	sudo apt install autoconf automake libtool
	sudo apt install valgrind # optional

- Install json-c(branch : master, commitID : 994e6c1)
	$ git clone https://github.com/json-c/json-c.git
	$ cd json-c
	$ sh autogen.sh
	$ ./configure  
	$ make
	$ make install
	
- set .bashrc 
	add below line in ~/.bashrc

	export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"

	and  command 
	
	source .bashrc

- Install rt-app(branch : master, commitID : aee41c5)
	$autoreconf --install
	$ ./configure
	$ make					---> get error here.

3. What I get (error log here)

> Making all in src
make[1]: Entering directory '/home/pino/workspace/rt-app/src'
make  all-am
make[2]: Entering directory '/home/pino/workspace/rt-app/src'
gcc -DHAVE_CONFIG_H -I.  -I./../libdl/   -g -O2 -MT rt-app_utils.o -MD -MP -MF .deps/rt-app_utils.Tpo -c -o rt-app_utils.o rt-app_utils.c
mv -f .deps/rt-app_utils.Tpo .deps/rt-app_utils.Po
gcc -DHAVE_CONFIG_H -I.  -I./../libdl/   -g -O2 -MT rt-app_args.o -MD -MP -MF .deps/rt-app_args.Tpo -c -o rt-app_args.o rt-app_args.c
mv -f .deps/rt-app_args.Tpo .deps/rt-app_args.Po
gcc -DHAVE_CONFIG_H -I.  -I./../libdl/   -g -O2 -MT rt-app.o -MD -MP -MF .deps/rt-app.Tpo -c -o rt-app.o rt-app.c
mv -f .deps/rt-app.Tpo .deps/rt-app.Po
gcc -DHAVE_CONFIG_H -I.  -I./../libdl/   -g -O2 -MT rt-app_parse_config.o -MD -MP -MF .deps/rt-app_parse_config.Tpo -c -o rt-app_parse_config.o rt-app_parse_config.c
rt-app_parse_config.c: In function ‘parse_resource_data’:
rt-app_parse_config.c:286:44: error: ‘TRUE’ undeclared (first use in this function)
  type = get_string_value_from(obj, "type", TRUE, def_type);
                                            ^
rt-app_parse_config.c:286:44: note: each undeclared identifier is reported only once for each function it appears in
rt-app_parse_config.c: In function ‘parse_thread_event_data’:
rt-app_parse_config.c:475:43: error: ‘TRUE’ undeclared (first use in this function)
   tmp = get_string_value_from(obj, "ref", TRUE, "unknown");
                                           ^
rt-app_parse_config.c: In function ‘parse_cpuset_data’:
rt-app_parse_config.c:657:42: error: ‘TRUE’ undeclared (first use in this function)
  cpuset_obj = get_in_object(obj, "cpus", TRUE);
                                          ^
rt-app_parse_config.c: In function ‘parse_sched_data’:
rt-app_parse_config.c:697:48: error: ‘TRUE’ undeclared (first use in this function)
  policy = get_string_value_from(obj, "policy", TRUE, def_str_policy);
                                                ^
rt-app_parse_config.c: In function ‘parse_thread_phase_data’:
rt-app_parse_config.c:763:47: error: ‘TRUE’ undeclared (first use in this function)
  data->loop = get_int_value_from(obj, "loop", TRUE, 1);
                                               ^
rt-app_parse_config.c: In function ‘parse_thread_data’:
rt-app_parse_config.c:824:49: error: ‘TRUE’ undeclared (first use in this function)
  data->delay = get_int_value_from(obj, "delay", TRUE, 0);
                                                 ^
rt-app_parse_config.c: In function ‘parse_tasks’:
rt-app_parse_config.c:894:50: error: ‘TRUE’ undeclared (first use in this function)
   instance = get_int_value_from(val, "instance", TRUE, 1);
                                                  ^
rt-app_parse_config.c: In function ‘parse_global’:
rt-app_parse_config.c:936:58: error: ‘TRUE’ undeclared (first use in this function)
  opts->duration = get_int_value_from(global, "duration", TRUE, -1);
                                                          ^
rt-app_parse_config.c: In function ‘get_opts_from_json_object’:
rt-app_parse_config.c:1036:41: error: ‘TRUE’ undeclared (first use in this function)
  global = get_in_object(root, "global", TRUE);
                                         ^
rt-app_parse_config.c:1040:39: error: ‘FALSE’ undeclared (first use in this function)
  tasks = get_in_object(root, "tasks", FALSE);
                                       ^
Makefile:484: recipe for target 'rt-app_parse_config.o' failed
make[2]: *** [rt-app_parse_config.o] Error 1
make[2]: Leaving directory '/home/pino/workspace/rt-app/src'
Makefile:335: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pino/workspace/rt-app/src'
Makefile:391: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by pino-kim** [comment]
Current jason-c remove TRUE and FALSE declare.
So I suggest if someone use previous version jason-c don't need to work it. 
I think It will not occur redefined warning message.

**Comment by jlelli** [comment]
I decided to squash your commits into one and created an new PR #65 (maintaining the authoriship).
Please have a look and see if it looks OK for you. :-)

**Comment by jlelli** [comment]
Closing since superseeded by #65.

**Pull request closed without merging**
